name: Integration Continue

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List files (for debugging)
        run: ls -la

      - name: Use Node.js 20.x (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

  integration-test:
    runs-on: ubuntu-latest
    needs: [frontend-test]
    steps:
      - name: Stop components
        run: |
          if [ -f docker-compose.build.yml ]; then
            docker compose -f docker-compose.build.yml down
          else
            echo "docker-compose.build.yml not found, skipping..."
          fi

  build-image:
    runs-on: ubuntu-latest
    needs: [integration-test]
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

    strategy:
      matrix:
        component: ["src/app"]

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.component }}
          file: ${{ matrix.component }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/spm-${{ matrix.component }}:${{ github.ref_name }}
