name: Sync Issues

on:
  issues:
    types: [opened, edited, closed, reopened]
  repository_dispatch:
    types: [gitlab_trigger]

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Execute sync script
        run: |
          python3  /home/gitlab-runner/scripts-secures/script_issue.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
