name: Sync Pull Requests

on:
  pull_request:
    types: [opened, edited, closed, reopened]
  repository_dispatch:
    types: [gitlab_trigger]

jobs:
  sync-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Execute sync script
        run: |
          python3 ./scripts-secures/script_pr.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
